---
title: "BubR1 Knockout Project"
author: "Aaron Mohammed"
date: "2023-07-06"
output: html_document
---

```{r setup, include=FALSE}

library(Seurat)
library(ggplot2)
library(SingleR)
library(celldex)
library(stringr)

proj_path <- "/Users/asm/Creighton/core_lab/scRNAseq_Ren"
seurats_path <- file.path(proj_path, "seurats")

output_path <- file.path(proj_path, "output")
dir.create(output_path)

celltype_umaps_path <- file.path(output_path, "celltype_umaps")
dir.create(celltype_umaps_path)

dge_path <- file.path(output_path, "dge_results")
dir.create(dge_path)

```

```{r}

# mouse_seurat <- readRDS(file.path(seurats_path, "integrated_mouse_seurat.rds"))

mouse_seurat <- readRDS(file.path(seurats_path, "annotated_mouse_seurat.rds"))


```

```{r}

# Annotation using SingleR
DefaultAssay(mouse_seurat) <- "RNA"

# Use Benayoun B et al. bulk RNA seq data as reference
mouse_ref <- MouseRNAseqData()

mouse_assay_dat <- GetAssayData(mouse_seurat)

pred_mouse_dat <- SingleR(test = mouse_assay_dat, 
                          ref = mouse_ref, 
                          labels = mouse_ref$label.main)


```

```{r}

seurat_row_names <- row.names(mouse_seurat@meta.data)
pred_row_names <- row.names(pred_mouse_dat)

# Add singleR annotation results to the seurat object
mouse_seurat <- AddMetaData(mouse_seurat, pred_mouse_dat$labels, col.name = "celltype_BenB")

# saveRDS(mouse_seurat, file.path(seurats_path, "annotated_mouse_seurat.rds"))

```

```{r}

DefaultAssay(mouse_seurat) <- "integrated"

mouse_seurat <- ScaleData(mouse_seurat, verbose = FALSE)
mouse_seurat <- RunPCA(mouse_seurat, npcs = 30, verbose = FALSE)
mouse_seurat <- RunUMAP(mouse_seurat, reduction = "pca", dims = 1:30)
mouse_seurat <- FindNeighbors(mouse_seurat, reduction = "pca", dims = 1:30)
mouse_seurat <- FindClusters(mouse_seurat, resolution = 0.5)

```

```{r}

Idents(mouse_seurat) <- "sample_id"
wild_sub <- subset(mouse_seurat, idents = "wildtype")
knock_sub <- subset(mouse_seurat, idents = "knockout")

```

```{r}

umap_wild_clust <- UMAPPlot(wild_sub, group.by="celltype_BenB", label = TRUE) + ggtitle("Wildtype UMAP")
umap_wild_clust

umap_knock_clust <- UMAPPlot(knock_sub, group.by="celltype_BenB", label = TRUE) + ggtitle("Knockout UMAP")
umap_knock_clust

```

```{r}

pdf(file.path(output_path, "wildtype_UMAP.pdf"), height = 10, width = 14)
umap_wild_clust
dev.off()

pdf(file.path(output_path, "knockout_UMAP.pdf"), height = 10, width = 14)
umap_knock_clust
dev.off()

```
```{r}

PCAPlot(wild_sub, group.by="celltype_BenB", label = TRUE) + ggtitle("Wildtype PCA")
PCAPlot(knock_sub, group.by="celltype_BenB", label = TRUE) + ggtitle("Knockout PCA")

```
```{r}

library(clusterProfiler)

wild_cardio_cellz <- CellSelector(umap_wild_clust)
unique(wild_sub@meta.data[wild_cardio_cellz,"seurat_clusters"])

cardio_clust_A <- 2
cardio_clust_B <- 8

knock_cardio_cellz <- CellSelector(umap_knock_clust)
unique(knock_sub@meta.data[knock_cardio_cellz,"seurat_clusters"])

knock_clust_A <- 2
knock_clust_B <- 8

```

```{r}

Idents(mouse_seurat) <- "seurat_clusters"

cardio_sub_A <- subset(mouse_seurat, idents = 2)
cardio_sub_B <- subset(mouse_seurat, idents = 8)

Idents(cardio_sub_A) <- "celltype_BenB"
Idents(cardio_sub_B) <- "celltype_BenB"

cardio_sub_A <- subset(cardio_sub_A, idents = "Cardiomyocytes")
cardio_sub_B <- subset(cardio_sub_B, idents = "Cardiomyocytes")

```

```{r}

# DGE analysis 
Idents(cardio_sub_A) <- "sample_id"
cardio_A_knock_vs_WT <- FindMarkers(cardio_sub_A, ident.1 = "knockout", ident.2 = "wildtype", logfc.threshold= 0)

Idents(cardio_sub_B) <- "sample_id"
cardio_B_knock_vs_WT <- FindMarkers(cardio_sub_B, ident.1 = "knockout", ident.2 = "wildtype", logfc.threshold= 0)

```
```{r}

cardio_A_knock_vs_WT <- cardio_A_knock_vs_WT[order(-cardio_A_knock_vs_WT$avg_log2FC), ]
cardio_B_knock_vs_WT <- cardio_B_knock_vs_WT[order(-cardio_B_knock_vs_WT$avg_log2FC), ]

```

```{r}

write.csv(cardio_A_knock_vs_WT, file.path(output_path, "knockout_vs_WT_right_cardio.csv"))
write.csv(cardio_B_knock_vs_WT, file.path(output_path, "knockout_vs_WT_left_cardio.csv"))

```

```{r}

library(EnhancedVolcano)


cardio_A_knock_vs_WT_plot <- EnhancedVolcano(cardio_A_knock_vs_WT, 
                x="avg_log2FC", y="p_val", 
                lab= row.names(cardio_A_knock_vs_WT),
                pCutoff = 0.05, FCcutoff = 0.3,
                title = "Knockout vs WT - Right Cardiomyocyte Cluster",
                subtitle = bquote(italic("FC cutoff = 0.3     p-value cutoff = 0.05")))

cardio_A_knock_vs_WT_plot

cardio_B_knock_vs_WT_plot <- EnhancedVolcano(cardio_B_knock_vs_WT, 
                x="avg_log2FC", y="p_val", 
                lab= row.names(cardio_B_knock_vs_WT),
                pCutoff = 0.05, FCcutoff = 0.3,
                title = "Knockout vs WT - Left Cardiomyocyte Cluster",
                subtitle = bquote(italic("FC cutoff = 0.3     p-value cutoff = 0.05")))

cardio_B_knock_vs_WT_plot

```

```{r}

pdf(file.path(output_path, "KO_vs_WT_right_cardio_plot.pdf"), height = 10, width = 14)
cardio_A_knock_vs_WT_plot
dev.off()

pdf(file.path(output_path, "KO_vs_WT_left_cardio_plot.pdf"), height = 10, width = 14)
cardio_B_knock_vs_WT_plot
dev.off()

```









